database:
  jdbcUrl: "jdbc:mysql://localhost:3306/minecraft_db?useSSL=false&autoReconnect=true"
  user: "minecraft_user"
  password: "securepassword"
  maxPoolSize: 10
  connectionTimeout: 30000   # milliseconds
  timeout: 300000            # milliseconds, idle timeout
  maxLifetime: 1800000       # milliseconds, max lifetime